### ISSUE TITLE
Investigate how to automate backups through to NAS

### ISSUE THREAD

**Issue by ahayzen** [ahayzen/nix-config#142]
- [x] VPS -> NAS (rsync)
- [x] Lab -> NAS (rsync)
- [x] NAS -> local snapshots (restic)
- [ ] NAS -> Offsite (restic)
- [ ] ~NAS -> removable storage (restic? script)~ #439

# Further possibles

- [ ] ~Restic REST server -> NAS~ #440
- [ ] ~Laptop / PC -> Restic REST server?~ #440 

But then how do we make these go offsite?

Likely using restic in containers, but do we need to run our backup scripts? Or we do have a service that is triggered periodically to create the db snapshots (probably yes)

**Comment by ahayzen** [comment]
- [ ] sshfs NAS <-> Lab
- [ ] restic REST API on Lab in append mode and users limited
- [ ] rathole of REST API to server
- [ ] restic from devices to server REST API

**Comment by ahayzen** [comment]
- [ ] use a timer to take snapshots and rotate them separately from manual backups?
