### ISSUE TITLE
Migrate OVH vps

### ISSUE THREAD

**Issue by ahayzen** [ahayzen/nix-config#3]
# Phase 1

Prepare the existing host data

- [x] Migrate db postgres to sqlite
- [x] Backup data
- [x] Ensure we have a route to having containers not built on the host
  - [x] Wagtail

# Phase 2

Prepare nix flake definition

- [x] Containers
  - [x] Caddy
  - [x] Wagtail
  - [ ] ~Proxy~ (using ssh on host for now)
  - [ ] ~Flathub Stats~ (disable?)
- [x] Generate correct hardware
- [x] Ensure updates work correctly
- [x] Solve user permissions as we'll have one user not many

# Phase 3

Deploy to the host

- [x] Purchase new VPS
- [x] Run nixos-anywhere
- [x] Restore data

# Phase 4

Improvements

- [ ] Look into newer hardening like crowdsec
- [ ] Further services
